---
openapi: 3.0.1
info:
  title: WD301 Capstone API
  version: 0.0.1
paths:
  "/articles":
    get:
      summary: list articles
      tags:
      - Articles
      responses:
        '200':
          description: successful
  "/articles/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Articles
      responses:
        '200':
          description: successful
  "/matches":
    get:
      summary: list matches
      tags:
      - Matches
      responses:
        '200':
          description: successful
  "/matches/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show match
      tags:
      - Matches
      responses:
        '200':
          description: successful
  "/sports":
    get:
      summary: list sports
      tags:
      - Sports
      responses:
        '200':
          description: successful
  "/sports/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show sport
      tags:
      - Sports
      responses:
        '200':
          description: successful
  "/teams":
    get:
      summary: list teams
      tags:
      - Teams
      responses:
        '200':
          description: successful
  "/teams/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show team
      tags:
      - Teams
      responses:
        '200':
          description: successful
  "/user":
    get:
      summary: user details
      tags:
      - Users
      security:
      - ApiKeyAuth: {}
      responses:
        '200':
          description: successful
  "/user/preferences":
    get:
      summary: get_preferences user
      tags:
      - Users
      security:
      - ApiKeyAuth: {}
      responses:
        '200':
          description: successful
    patch:
      summary: update_preferences user
      tags:
      - Users
      security:
      - ApiKeyAuth: {}
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                preferences:
                  type: object
              required:
              - preferences
  "/user/password":
    patch:
      summary: update_password user
      tags:
      - Users
      security:
      - ApiKeyAuth: {}
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                new_password:
                  type: string
              required:
              - current_password
              - new_password
  "/users/sign_in":
    post:
      summary: sign_in user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/users":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: user created
          content:
            application/json:
              examples:
                example_0:
                  value:
                    user:
                      id: 1
                      name: John Doe
                      email: user9@example.com
                      preferences: {}
                    auth_token: e7edbdb39a4b517a268c88e0fffae0e4fa34f793b5b717ae06868b123f3704821685478335
        '422':
          description: unprocessable entity
          content:
            application/json:
              examples:
                example_0:
                  value:
                    errors:
                    - Password can't be blank
                    - Name can't be blank
                    - Email can't be blank
                    - Email is invalid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
              example:
                name: John Doe
                email: user9@example.com
                password: StrongPassword@99
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: Authorization
      in: header
servers:
- url: https://{hostWithSSL}
  variables:
    hostWithSSL:
      default: wd301-capstone-api.pupilfirst.school
- url: http://{hostWithoutSSL}
  variables:
    hostWithoutSSL:
      default: localhost:5000
